spring:
  application:
    name: arxiv-daily-report

  ai:
    openai:
      api-key:
      chat:
        model: gpt-4o

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  task:
    scheduling:
      pool:
        size: 2

logging:
  level:
    org.springframework.ai: debug
    com.example: debug