spring:
  application:
    name: arxiv-daily-report
  config:
    import: optional:file:.env[.properties]

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
    vectorstore:
      qdrant:
        host: ${DB_HOST}
        collection-name: papers
        port: ${QDRANT_GRPC_PORT}
        use-tls: false
        initialize-schema: true


  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  task:
    scheduling:
      pool:
        size: 2

  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.ai: debug
    com.example: debug